version: '3'

services:
  nginx: 
    build:
      context: ./requirements/nginx/
    container_name: nginx
    restart:  always
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - my_network
    volumes:
      - wordpress:/var/www/html/wordpress
  wordpress:
    build:
      context: ./requirements/wordpress/
    container_name: wordpress
    restart: always
    ports:
        - "9000:9000"
    networks:
      - my_network
    volumes:
      - wordpress:/var/www/html/wordpress
networks:
  my_network:
volumes:
  wordpress: